plugins {
    id 'java'
    id 'application'
}

group 'com.parax'
version '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.java-websocket:Java-WebSocket:1.5.3'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'org.apache.httpcomponents.client5:httpclient5:5.2.1'
}

application {
    mainClass = 'com.parax.bot.example.MyParaxBot'
}
